[project]
name = "online-cinema-project"
version = "0.1.0"
description = "Backend platform for an online movie theater"
authors = [
    {name = "Illia Savinov",email = "dresar2404@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi (>=0.141.1,<0.142.0)",
    "uvicorn (>=0.52.0,<0.53.0)",
    "python-multipart (>=0.0.32,<0.0.33)",
    "sqlalchemy (>=2.0.51,<3.0.0)",
    "alembic (>=1.18.5,<2.0.0)",
    "asyncpg (>=0.31.0,<0.32.0)",
    "pydantic (>=2.13.4,<3.0.0)",
    "pydantic-settings (>=2.14.2,<3.0.0)",
    "email-validator (>=2.3.0,<3.0.0)",
    "python-jose (>=3.5.0,<4.0.0)",
    "passlib (>=1.7.4,<2.0.0)",
    "bcrypt (<4.1.0)",
    "celery (>=5.6.3,<6.0.0)",
    "redis (>=8.1.0,<9.0.0)",
    "celery-pool-asyncio (>=0.2.0,<0.3.0)",
    "boto3 (>=1.43.60,<2.0.0)",
    "stripe (>=15.4.0,<16.0.0)",
    "httpx (>=0.28.1,<0.29.0)",
    "aiofiles (>=25.1.0,<26.0.0)",
    "aiosmtplib (>=5.1.2,<6.0.0)"
]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[dependency-groups]
dev = [
    "watchfiles (>=1.2.0,<2.0.0)",
    "pytest (>=9.1.1,<10.0.0)",
    "pytest-asyncio (>=1.4.0,<2.0.0)",
    "black (>=26.5.1,<27.0.0)",
    "flake8 (>=7.3.0,<8.0.0)",
    "mypy (>=2.3.0)"
]

[tool.poetry]
package-mode = false


[tool.poetry.group.dev.dependencies]
aiosqlite = "^0.22.1"
testcontainers = {extras = ["postgresql"], version = "^4.15.0"}

[tool.mypy]
plugins = ["pydantic.mypy"]
exclude = [
    "^\\.venv/",
    "^venv/",
    "^alembic/versions/",
    "^__pycache__/"
]
warn_unused_ignores = true
warn_return_any = false
check_untyped_defs = true

[tool.pytest.ini_options]
asyncio_mode = "auto"
asyncio_default_fixture_loop_scope = "session"
asyncio_default_test_loop_scope = "session"

[[tool.mypy.overrides]]
module = [
    "celery.*",
    "boto3.*",
    "botocore.*",
    "jose.*",
    "passlib.*"
]
ignore_missing_imports = true

[tool.pydantic-mypy]
init_forbid_extra = true
init_typed = true
warn_required_dynamic_aliases = true

