"""Add orders and order items tables

Revision ID: 8947bbcbf392
Revises: 5ba0b3e2fa5c
Create Date: 2026-07-27 18:42:54.307892

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8947bbcbf392'
down_revision: Union[str, Sequence[str], None] = '5ba0b3e2fa5c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orders',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('status', sa.Enum('pending', 'paid', 'canceled', name='statusenum'), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('order_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('movie_id', sa.Integer(), nullable=False),
    sa.Column('price_at_order', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['movie_id'], ['movies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('movie_purchases', sa.Column('order_id', sa.Integer(), nullable=True))
    op.create_foreign_key(
        'fk_movie_purchases_order_id_orders',
        'movie_purchases',
        'orders',
        ['order_id'],
        ['id'],
        ondelete='SET NULL'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_movie_purchases_order_id_orders', 'movie_purchases', type_='foreignkey')
    op.drop_column('movie_purchases', 'order_id')
    op.drop_table('order_items')
    op.drop_table('orders')

    sa.Enum(name="statusenum").drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
